### ISSUE TITLE
Discussion: Should this be folded into an existing module?

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-test-utils#9]
In https://github.com/lightblue-platform/lightblue-rest/pull/124 a new rest-test module is being created. I am creating this issue only to discuss if it would be desirable to merge this into that existing project?

@paterczm thoughts?

**Comment by luan-cestari** [comment]
I think it might be nice to have this repository under the rest repository as a module because as far I can see this repository provides just test utilities for code that want to use the rest services provided in the rest repository. In summary, as it is very tightly coupled, we could move the code here to have one or more modules under https://github.com/lightblue-platform/lightblue-rest , maybe even merging with the https://github.com/lightblue-platform/lightblue-rest/tree/master/rest-test project and avoiding to create a cyclic dependency graph (maven won't build). 

This would also help to we have the maven dependency management set properly, as in the current parent pom file ( https://github.com/dcrissman/lightblue-test-utils/blob/jcl-over-slf4j/pom.xml) doesn't have declared the dependencies versions and scopes of its modules ( such as   https://github.com/dcrissman/lightblue-test-utils/blob/jcl-over-slf4j/test-utils/pom.xml ) (just like what happens in other projects , for example https://github.com/lightblue-platform/lightblue-rest/blob/master/pom.xml   and  https://github.com/lightblue-platform/lightblue-rest/blob/master/metadata/pom.xml )

**Comment by dcrissman** [comment]
Thinking about this more, this would make lightblue-rest dependent on lightblue-client. If anything, it should be the other way around with the client being dependent on rest. Any application using client that would want to do integration testing, would obviously already have the client available.

**Comment by dcrissman** [comment]
What if we split AbstractCRUDControllerWithRest into two classes, the first essentially being the same thing as it is today, but without any LightblueClient references. This could then live in lightblue-rest. 

Then the remaining lightblue-client functions could be a sub-class of AbstractCRUDControllerWithRest that lives in lightblue-client/test.

Thoughts?

**Comment by paterczm** [comment]
Merged both PRs. I'm not sure why you still need lightblue-test-utils (you added it to https://github.com/dcrissman/lightblue-client/blob/move-client-functionality/pom.xml)?

**Comment by dcrissman** [comment]
@paterczm I just created two follow up PRs that will remove lightblue-test-utils altogether.

**Comment by dcrissman** [comment]
Completed
